In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playbyplay
jordan_id = 893
jordan_team_id = 1610612741

In [3]:
# Query for the last regular season game where the Pacers were playing
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.library.parameters import Season
from nba_api.stats.library.parameters import SeasonType

gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable = jordan_team_id,
                            season_nullable=Season.default,
                            season_type_nullable=SeasonType.regular)  

games_dict = gamefinder.get_normalized_dict()
games = games_dict['LeagueGameFinderResults']
game = games[0]
game_id = game['GAME_ID']
game_matchup = game['MATCHUP']

In [4]:
from nba_api.stats.endpoints import playbyplay
df = playbyplay.PlayByPlay(game_id).get_data_frames()[0]
df.head(10)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN
0,0022201223,2,12,0,1,1:13 PM,12:00,None,Start of 1st Period (1:13 PM EST),None,None,None
1,0022201223,4,10,0,1,1:13 PM,12:00,Jump Ball Vucevic vs. Wiseman: Tip to LaVine,None,None,None,None
2,0022201223,7,1,47,1,1:13 PM,11:40,DeRozan 9' Turnaround Jump Shot (2 PTS),None,None,0 - 2,2
3,0022201223,9,1,6,1,1:14 PM,11:18,None,None,Hayes 2' Driving Layup (2 PTS),2 - 2,TIE
4,0022201223,10,2,1,1,1:14 PM,11:02,MISS LaVine 21' Jump Shot,None,None,None,None
5,0022201223,11,4,0,1,1:14 PM,10:56,None,None,Hayes REBOUND (Off:0 Def:1),None,None
6,0022201223,12,2,1,1,1:14 PM,10:53,None,None,MISS Ivey 27' 3PT Jump Shot,None,None
7,0022201223,13,4,0,1,1:14 PM,10:51,DeRozan REBOUND (Off:0 Def:1),None,None,None,None
8,0022201223,14,1,52,1,1:14 PM,10:48,LaVine Alley Oop Dunk (2 PTS) (DeRozan 1 AST),None,None,2 - 4,2
9,0022201223,16,6,1,1,1:14 PM,10:32,Caruso P.FOUL (P1.T1) (M.Smith),None,None,None,None

In [5]:
import pandas
pandas.set_option('display.max_colwidth',500)
pandas.set_option('display.max_rows',500)

In [6]:
from enum import Enum

class EventMsgType(Enum):
    FIELD_GOAL_MADE = 1
    FIELD_GOAL_MISSED = 2
    FREE_THROWfree_throw_attempt = 3
    REBOUND = 4
    TURNOVER = 5
    FOUL = 6
    VIOLATION = 7
    SUBSTITUTION = 8
    TIMEOUT = 9
    JUMP_BALL = 10
    EJECTION = 11
    PERIOD_BEGIN = 12
    PERIOD_END = 13

In [12]:
df.loc[df['EVENTMSGTYPE'] == 4].head(5)

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN
5,0022201223,11,4,0,1,1:14 PM,10:56,None,None,Hayes REBOUND (Off:0 Def:1),None,None
7,0022201223,13,4,0,1,1:14 PM,10:51,DeRozan REBOUND (Off:0 Def:1),None,None,None,None
11,0022201223,20,4,0,1,1:15 PM,10:18,Caruso REBOUND (Off:0 Def:1),None,None,None,None
14,0022201223,24,4,0,1,1:15 PM,10:00,None,None,Wiseman REBOUND (Off:1 Def:0),None,None
20,0022201223,34,4,0,1,1:17 PM,8:53,None,None,Wiseman REBOUND (Off:2 Def:0),None,None

In [9]:
import re
import operator

#the following expression is specific to EventMsgType 1
p = re.compile('(\s{2}|\' )([\w+ ]+)')

#get the PlayByPlay data from the Pacers game_id
plays = playbyplay.PlayByPlay(game_id).get_normalized_dict()['PlayByPlay']

#declare a few variables
description = ''
event_msg_action_types = {}

#loop over the play by play data
for play in plays:
    if play['EVENTMSGTYPE'] == 1:
        if play['HOMEDESCRIPTION']:
            description = play['HOMEDESCRIPTION']
        else:
            description = play['VISITORDESCRIPTION']
        if p.search(description):
            #do a bit of searching(regex) and a little character magic: underscores and upper case
            event_msg_action = re.sub(' ', '_', p.search(description).groups()[1].rstrip()).upper()
            #Add it to our dictionary
            event_msg_action_types[event_msg_action] = play['EVENTMSGACTIONTYPE']
            
#sort it all
event_msg_action_types = sorted(event_msg_action_types.items(), key=operator.itemgetter(0))

#output a class that we could plug into our code base
for action in event_msg_action_types:
    print(f'\t{action[0]} = {action[1]}')

	3PT_JUMP_SHOT = 1
	3PT_PULLUP_JUMP_SHOT = 79
	3PT_STEP_BACK_JUMP_SHOT = 80
	CUTTING_LAYUP_SHOT = 98
	DRIVING_FINGER_ROLL_LAYUP = 75
	DRIVING_FLOATING_BANK_JUMP_SHOT = 102
	DRIVING_FLOATING_JUMP_SHOT = 101
	DRIVING_HOOK_SHOT = 57
	DRIVING_LAYUP = 6
	DUNK = 7
	FLOATING_JUMP_SHOT = 78
	JUMP_SHOT = 1
	LAYUP = 5
	PULLUP_JUMP_SHOT = 79
	RUNNING_LAYUP = 41
	STEP_BACK_JUMP_SHOT = 80
	TURNAROUND_HOOK_SHOT = 58
	TURNAROUND_JUMP_SHOT = 47

In [10]:
#get the PlayByPlay data from the Pacers game_id
plays = playbyplay.PlayByPlay(game_id).get_normalized_dict()['PlayByPlay']

#declare a few variables
description = ''
event_msg_action_types = {}

#loop over the play by play data
#do a bit of findall(regex) and a little character magic: underscores and upper case
#we're using a findall here as we have to deal with the extra word MISS at the beginning of the text.
#that extra text means we'll have multiple matches for our regex.
for play in plays:
    if play['EVENTMSGTYPE'] == 2:
        match = list()
        if play['HOMEDESCRIPTION'] is not None: 
            match = p.findall(play['HOMEDESCRIPTION'])

            #looking for blocks
            if len(match) & (play['VISITORDESCRIPTION'] is not None):
                print(play['VISITORDESCRIPTION'])

        else:
            match = p.findall(play['VISITORDESCRIPTION'])
            
            #looking for blocks
            if len(match) & (play['HOMEDESCRIPTION'] is not None):
                print(play['HOMEDESCRIPTION'])
        if match:
            event_msg_action = re.sub(' ', '_', match[0][1]).upper()
            event_msg_action_types[event_msg_action] = play['EVENTMSGACTIONTYPE']
            
event_msg_action_types = sorted(event_msg_action_types.items(), key=operator.itemgetter(0))

print("")
for action in event_msg_action_types:
    print(f'{action[0]} = {action[1]}')

Wiseman BLOCK (1 BLK)
Duren BLOCK (1 BLK)
Hayes BLOCK (1 BLK)

3PT_JUMP_SHOT = 1
3PT_PULLUP_JUMP_SHOT = 79
3PT_STEP_BACK_JUMP_SHOT = 80
ALLEY_OOP_LAYUP = 43
DRIVING_DUNK = 9
DRIVING_FLOATING_BANK_JUMP_SHOT = 102
DRIVING_FLOATING_JUMP_SHOT = 101
DRIVING_HOOK_SHOT = 57
DRIVING_LAYUP = 6
DRIVING_REVERSE_LAYUP = 73
FADEAWAY_JUMPER = 63
FLOATING_JUMP_SHOT = 78
JUMP_SHOT = 1
LAYUP = 5
PULLUP_JUMP_SHOT = 79
PUTBACK_LAYUP = 72
RUNNING_LAYUP = 41
TIP_LAYUP_SHOT = 97
TURNAROUND_JUMP_SHOT = 47

In [4]:
play = pd.read_csv("play_by_play.csv")
play.columns

Index(['game_id', 'eventnum', 'eventmsgtype', 'eventmsgactiontype', 'period',
       'wctimestring', 'pctimestring', 'homedescription', 'neutraldescription',
       'visitordescription', 'score', 'scoremargin', 'person1type',
       'player1_id', 'player1_name', 'player1_team_id', 'player1_team_city',
       'player1_team_nickname', 'player1_team_abbreviation', 'person2type',
       'player2_id', 'player2_name', 'player2_team_id', 'player2_team_city',
       'player2_team_nickname', 'player2_team_abbreviation', 'person3type',
       'player3_id', 'player3_name', 'player3_team_id', 'player3_team_city',
       'player3_team_nickname', 'player3_team_abbreviation',
       'video_available_flag'],
      dtype='object')

In [20]:
play["player1_name"]

1383           Popeye Jones
1385           Popeye Jones
1386           Popeye Jones
1389           Popeye Jones
1390           Popeye Jones
                 ...
13225937      Herbert Jones
13225943      Herbert Jones
13225959      Herbert Jones
13225960    Trey Murphy III
13225962    Trey Murphy III
Name: player1_name, Length: 121655, dtype: object

In [4]:
play = play.drop(['player1_name', 'player1_team_id', 'player1_team_city',
       'player1_team_nickname', 'player1_team_abbreviation', 'player2_team_city',
       'player2_team_nickname', 'player2_team_abbreviation', 'player3_name', 'player3_team_id', 'player3_team_city',
       'player3_team_nickname', 'player3_team_abbreviation', 'video_available_flag', 'person1type', 'person2type', 'person3type'], axis = 1)

In [33]:
temp = game_summ.loc[game_summ["season"] == 1984]
for i in [1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998]:
    temp = temp.append(game_summ.loc[game_summ["season"] == i])
game_summ = temp
temp = pd.DataFrame()
game_summ

,game_date_est,game_sequence,game_id,game_status_id,game_status_text,gamecode,home_team_id,visitor_team_id,season,live_period,live_pc_time,natl_tv_broadcaster_abbreviation,live_period_time_bcast,wh_status
19822,1984-10-26 00:00:00,NaN,28400002,3,NaN,19841026/CLEPHL,1610612755,1610612739,1984,4,NaN,NaN,Q4 -,1
19823,1984-10-26 00:00:00,NaN,28400006,3,NaN,19841026/PHXGOS,1610612744,1610612756,1984,4,NaN,NaN,Q4 -,1
19824,1984-10-26 00:00:00,NaN,28400003,3,NaN,19841026/BOSDET,1610612765,1610612738,1984,4,NaN,NaN,Q4 -,1
19825,1984-10-26 00:00:00,NaN,28400005,3,NaN,19841026/WASCHI,1610612741,1610612764,1984,4,NaN,NaN,Q4 -,1
19826,1984-10-26 00:00:00,NaN,28400001,3,NaN,19841026/UTHSEA,1610612760,1610612762,1984,4,NaN,NaN,Q4 -,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34031,1999-05-05 00:00:00,9.0,29800721,3,Final,19990505/MINPHX,1610612756,1610612750,1998,4,NaN,NaN,Q4 -,1
34032,1999-05-05 00:00:00,6.0,29800718,3,Final,19990505/CLETOR,1610612761,1610612739,1998,4,NaN,NaN,Q4 -,1
34033,1999-05-05 00:00:00,2.0,29800714,3,Final,19990505/MIANYK,1610612752,1610612748,1998,4,NaN,NaN,Q4 -,1
34034,1999-05-05 00:00:00,13.0,29800725,3,Final,19990505/VANSAC,1610612758,1610612763,1998,4,NaN,NaN,Q4 -,1
34035,1999-05-05 00:00:00,4.0,29800716,3,Final,19990505/DETPHI,1610612755,1610612765,1998,5,NaN,NaN,Q5 -,1

In [34]:
game_ids = game_summ[game_summ["visitor_team_id"] == jordan_team_id]["game_id"].values.tolist()
temp = game_summ[game_summ["home_team_id"] == jordan_team_id]["game_id"].values.tolist()
for i in temp:
    game_ids.append(i)

In [35]:
temp = play.loc[play["game_id"] == game_ids.pop(0)]
for i in game_ids:
    temp = temp.append(play.loc[play["game_id"] == i])
play = temp
play

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,score,scoremargin,player1_id,player2_id,player2_name,player2_team_id,player3_id
4272,29600001,1,12,0,1,11:15 PM,12:00,NaN,Start of 1st Period (11:15 PM EST),NaN,NaN,NaN,0,0,NaN,NaN,0
4273,29600001,2,10,0,1,11:16 PM,12:00,Jump Ball Ellison vs. Longley: Tip to Harper,NaN,NaN,NaN,NaN,442,26,Luc Longley,1.610613e+09,166
4274,29600001,4,1,5,1,11:16 PM,11:39,NaN,NaN,Rodman Layup (2 PTS) (Longley 1 AST),2 - 0,-2,23,26,Luc Longley,1.610613e+09,0
4275,29600001,5,6,2,1,11:16 PM,11:39,Ellison S.FOUL (P1.T1),NaN,NaN,NaN,NaN,442,0,NaN,NaN,0
4276,29600001,6,3,10,1,11:17 PM,11:39,NaN,NaN,Rodman Free Throw 1 of 1 (3 PTS),3 - 0,-3,23,0,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339819,29800719,419,2,1,4,1:56 AM,0:28,MISS LaRue 24' 3PT Jump Shot,NaN,NaN,NaN,NaN,1601,0,NaN,NaN,0
1339820,29800719,420,4,0,4,1:56 AM,0:26,NaN,NaN,Wilkins REBOUND (Off:0 Def:2),NaN,NaN,1122,0,NaN,NaN,0
1339821,29800719,421,1,5,4,1:56 AM,0:23,NaN,NaN,Strong Layup (10 PTS) (Wilkins 1 AST),103 - 81,-22,400,1122,Dominique Wilkins,1.610613e+09,0
1339822,29800719,422,1,5,4,1:56 AM,0:05,Benjamin Layup (4 PTS),NaN,NaN,103 - 83,-20,1736,0,NaN,NaN,0
1339823,29800719,423,13,0,4,1:56 AM,0:00,NaN,End of 4th Period (1:56 AM EST),NaN,103 - 83,-20,0,0,NaN,NaN,0

In [36]:
play.head(20)

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,score,scoremargin,player1_id,player2_id,player2_name,player2_team_id,player3_id
4272,29600001,1,12,0,1,11:15 PM,12:00,NaN,Start of 1st Period (11:15 PM EST),NaN,NaN,NaN,0,0,NaN,NaN,0
4273,29600001,2,10,0,1,11:16 PM,12:00,Jump Ball Ellison vs. Longley: Tip to Harper,NaN,NaN,NaN,NaN,442,26,Luc Longley,1.610613e+09,166
4274,29600001,4,1,5,1,11:16 PM,11:39,NaN,NaN,Rodman Layup (2 PTS) (Longley 1 AST),2 - 0,-2,23,26,Luc Longley,1.610613e+09,0
4275,29600001,5,6,2,1,11:16 PM,11:39,Ellison S.FOUL (P1.T1),NaN,NaN,NaN,NaN,442,0,NaN,NaN,0
4276,29600001,6,3,10,1,11:17 PM,11:39,NaN,NaN,Rodman Free Throw 1 of 1 (3 PTS),3 - 0,-3,23,0,NaN,NaN,0
4277,29600001,7,1,1,1,11:17 PM,11:06,Wesley 20' Jump Shot (2 PTS),NaN,NaN,3 - 2,-1,133,0,NaN,NaN,0
4278,29600001,43,2,1,1,11:17 PM,11:06,NaN,NaN,MISS Jordan 15' Jump Shot,NaN,NaN,893,0,NaN,NaN,0
4279,29600001,44,4,0,1,11:17 PM,11:06,Wesley REBOUND (Off:0 Def:1),NaN,NaN,NaN,NaN,133,0,NaN,NaN,0
4280,29600001,8,1,6,1,11:17 PM,11:02,Williams Driving Layup (2 PTS) (Wesley 1 AST),NaN,NaN,3 - 4,1,677,133,David Wesley,1.610613e+09,0
4281,29600001,9,1,5,1,11:17 PM,10:46,NaN,NaN,Pippen Layup (2 PTS) (Longley 2 AST),5 - 4,-1,937,26,Luc Longley,1.610613e+09,0
4282,29600001,10,5,1,1,11:18 PM,10:34,Williams Bad Pass Turnover (P1.T1),NaN,Harper STEAL (1 STL),NaN,NaN,677,166,Ron Harper,1.610613e+09,0
4283,29600001,11,1,7,1,11:18 PM,10:29,NaN,NaN,Pippen Dunk (4 PTS) (Harper 1 AST),7 - 4,-3,937,166,Ron Harper,1.610613e+09,0
4284,29600001,12,5,4,1,11:18 PM,10:15,Ellison Traveling Turnover (P1.T2),NaN,NaN,NaN,NaN,442,0,NaN,NaN,0
4285,29600001,13,1,3,1,11:18 PM,9:59,NaN,NaN,Pippen 8' Hook Shot (6 PTS),9 - 4,-5,937,0,NaN,NaN,0
4286,29600001,14,2,5,1,11:19 PM,9:46,MISS Williams Layup,NaN,NaN,NaN,NaN,677,0,NaN,NaN,0
4287,29600001,15,4,0,1,11:19 PM,9:45,NaN,NaN,Pippen REBOUND (Off:0 Def:1),NaN,NaN,937,0,NaN,NaN,0
4288,29600001,16,5,4,1,11:19 PM,9:23,NaN,NaN,Longley Traveling Turnover (P1.T1),NaN,NaN,26,0,NaN,NaN,0
4289,29600001,17,2,1,1,11:19 PM,9:09,MISS Wesley 24' 3PT Jump Shot,NaN,NaN,NaN,NaN,133,0,NaN,NaN,0
4290,29600001,18,4,0,1,11:20 PM,9:06,Ellison REBOUND (Off:1 Def:0),NaN,NaN,NaN,NaN,442,0,NaN,NaN,0
4291,29600001,19,1,5,1,11:20 PM,9:06,Ellison Layup (2 PTS),NaN,NaN,9 - 6,-3,442,0,NaN,NaN,0

In [39]:
found = False
to_be_deleted = []
for row in play.iterrows():
    if not pd.isna(row[1]["visitordescription"]):
        if "Jordan" in row[1]["visitordescription"]:
            found = True
    if not pd.isna(row[1]["homedescription"]):
        if "Jordan" in row[1]["homedescription"]:
            found = True
    if not found: 
        to_be_deleted.append(row[0])
    found = False
play = play.drop(to_be_deleted)

In [40]:
play

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,score,scoremargin,player1_id,player2_id,player2_name,player2_team_id,player3_id
4278,29600001,43,2,1,1,11:17 PM,11:06,NaN,NaN,MISS Jordan 15' Jump Shot,NaN,NaN,893,0,NaN,NaN,0
4310,29600001,38,2,1,1,11:24 PM,7:01,NaN,NaN,MISS Jordan 25' 3PT Jump Shot,NaN,NaN,893,0,NaN,NaN,0
4320,29600001,50,4,0,1,11:27 PM,5:58,NaN,NaN,Jordan REBOUND (Off:0 Def:1),NaN,NaN,893,0,NaN,NaN,0
4327,29600001,57,1,1,1,11:30 PM,5:00,NaN,NaN,Jordan 16' Jump Shot (2 PTS),13 - 17,4,893,0,NaN,NaN,0
4335,29600001,65,1,1,1,11:32 PM,3:53,NaN,NaN,Jordan 17' Jump Shot (4 PTS) (Harper 3 AST),17 - 17,TIE,893,166,Ron Harper,1.610613e+09,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022688,29701177,440,2,5,4,2:51 PM,2:44,MISS Jordan Layup,NaN,NaN,NaN,NaN,893,0,NaN,NaN,0
1022697,29701177,449,3,11,4,2:55 PM,2:16,MISS Jordan Free Throw 1 of 2,NaN,NaN,NaN,NaN,893,0,NaN,NaN,0
1022700,29701177,453,3,12,4,2:55 PM,2:16,Jordan Free Throw 2 of 2 (42 PTS),NaN,NaN,102 - 105,3,893,0,NaN,NaN,0
1022718,29701177,474,3,11,4,3:05 PM,0:24,Jordan Free Throw 1 of 2 (43 PTS),NaN,NaN,105 - 108,3,893,0,NaN,NaN,0
1022719,29701177,475,3,12,4,3:06 PM,0:24,Jordan Free Throw 2 of 2 (44 PTS),NaN,NaN,105 - 109,4,893,0,NaN,NaN,0

In [59]:
play[play["eventmsgtype"] == 11]

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
3181817,20200655,471,11,4,4,12:33 PM,0:10,NaN,NaN,Jones Ejection:Other,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
3366271,20201077,409,11,4,4,9:03 PM,6:56,Jones Ejection:Other,NaN,NaN,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
3747430,20300777,447,11,1,4,9:55 PM,8:21,NaN,NaN,Jones Ejection:Second Technical,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
4640516,20500412,397,11,4,4,12:49 AM,6:00,NaN,NaN,E. Jones Ejection:Other,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
5058534,20600129,429,11,1,4,9:10 PM,4:32,NaN,NaN,Jones Ejection:Second Technical,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
7276705,21000381,440,11,1,4,8:57 PM,11:28,S. Jones Ejection:Second Technical,NaN,NaN,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
8035820,21100934,175,11,3,2,9:02 PM,6:05,Jones Ejection:First Flagrant Type 2,NaN,NaN,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
12701869,22101071,404,11,4,3,8:32 PM,6:22,NaN,NaN,Jones Ejection:Other,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1

In [17]:
temp = play.loc[(play["eventmsgtype"] == 8)]

In [19]:
play.head(50)

,game_id,eventnum,eventmsgtype,eventmsgactiontype,period,wctimestring,pctimestring,homedescription,neutraldescription,visitordescription,...,player2_team_nickname,player2_team_abbreviation,person3type,player3_id,player3_name,player3_team_id,player3_team_city,player3_team_nickname,player3_team_abbreviation,video_available_flag
0,29600009,2,12,0,1,11:44 PM,12:00,NaN,Start of 1st Period (11:44 PM EST),NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
1,29600009,3,10,0,1,11:45 PM,12:00,Jump Ball Olajuwon vs. Polynice: Tip to Willia...,NaN,NaN,...,Kings,SAC,5.0,722,Corliss Williamson,1.610613e+09,Sacramento,Kings,SAC,0
2,29600009,4,5,4,1,11:46 PM,11:49,NaN,NaN,Williamson Traveling Turnover (P1.T1),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
3,29600009,5,2,1,1,11:46 PM,11:27,MISS Olajuwon 13' Jump Shot,NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
4,29600009,7,4,0,1,11:46 PM,11:23,Drexler REBOUND (Off:1 Def:0),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
5,29600009,6,2,5,1,11:46 PM,11:23,MISS Drexler Layup,NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
6,29600009,8,4,0,1,11:46 PM,11:22,Olajuwon REBOUND (Off:1 Def:0),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
7,29600009,9,1,2,1,11:46 PM,11:18,Elie 10' Running Jump Shot (2 PTS) (Olajuwon 1...,NaN,NaN,...,Rockets,HOU,0.0,0,NaN,NaN,NaN,NaN,NaN,0
8,29600009,10,1,1,1,11:47 PM,11:00,NaN,NaN,Abdul-Rauf 9' Jump Shot (2 PTS),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
9,29600009,11,1,6,1,11:47 PM,10:44,Maloney Driving Layup (2 PTS) (Drexler 1 AST),NaN,NaN,...,Rockets,HOU,0.0,0,NaN,NaN,NaN,NaN,NaN,0
10,29600009,12,2,1,1,11:47 PM,10:27,NaN,NaN,MISS Williamson 13' Jump Shot,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
11,29600009,13,4,0,1,11:47 PM,10:26,NaN,NaN,Polynice REBOUND (Off:1 Def:0),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
12,29600009,14,1,5,1,11:47 PM,10:21,NaN,NaN,Williamson Layup (2 PTS) (Polynice 1 AST),...,Kings,SAC,0.0,0,NaN,NaN,NaN,NaN,NaN,0
13,29600009,15,2,1,1,11:47 PM,10:10,MISS Elie 24' 3PT Jump Shot,NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
14,29600009,16,4,0,1,11:47 PM,10:09,NaN,NaN,Williamson REBOUND (Off:0 Def:1),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
15,29600009,17,1,1,1,11:48 PM,9:58,NaN,NaN,Williamson 7' Jump Shot (4 PTS) (Richmond 1 AST),...,Kings,SAC,0.0,0,NaN,NaN,NaN,NaN,NaN,0
16,29600009,18,2,1,1,11:48 PM,9:43,MISS Elie 9' Jump Shot,NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
17,29600009,19,4,0,1,11:48 PM,9:42,NaN,NaN,Polynice REBOUND (Off:1 Def:1),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
18,29600009,20,2,1,1,11:48 PM,9:35,NaN,NaN,MISS Abdul-Rauf 3PT Jump Shot,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
19,29600009,21,4,0,1,11:48 PM,9:33,Willis REBOUND (Off:0 Def:1),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
20,29600009,22,1,1,1,11:48 PM,9:18,Elie 3PT Jump Shot (5 PTS) (Drexler 2 AST),NaN,NaN,...,Rockets,HOU,0.0,0,NaN,NaN,NaN,NaN,NaN,0
21,29600009,23,2,5,1,11:49 PM,8:59,NaN,NaN,MISS Grant Layup,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
22,29600009,24,4,0,1,11:49 PM,8:58,NaN,NaN,Kings Rebound,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
23,29600009,25,2,1,1,11:49 PM,8:49,NaN,NaN,MISS Richmond 3PT Jump Shot,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
24,29600009,26,4,0,1,11:49 PM,8:48,Drexler REBOUND (Off:1 Def:1),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
25,29600009,27,2,1,1,11:49 PM,8:38,MISS Willis 11' Jump Shot,NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
26,29600009,28,4,0,1,11:49 PM,8:37,NaN,NaN,Richmond REBOUND (Off:0 Def:1),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
27,29600009,29,2,5,1,11:49 PM,8:24,NaN,NaN,MISS Williamson Layup,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
28,29600009,30,4,0,1,11:49 PM,8:23,Olajuwon REBOUND (Off:1 Def:1),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
29,29600009,31,7,6,1,11:50 PM,8:15,NaN,NaN,Polynice Violation:Double Lane,...,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,0
30,29600009,32,2,5,1,11:50 PM,8:08,MISS Willis Layup,NaN,Richmond BLOCK (1 BLK),...,NaN,NaN,5.0,782,Mitch Richmond,1.610613e+09,Sacramento,Kings,SAC,0
31,29600009,34,4,0,1,11:50 PM,8:05,Olajuwon REBOUND (Off:2 Def:1),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
32,29600009,33,2,1,1,11:50 PM,8:05,MISS Olajuwon 8' Jump Shot,NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
33,29600009,35,4,0,1,11:50 PM,8:04,NaN,NaN,Richmond REBOUND (Off:0 Def:2),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
34,29600009,36,5,4,1,11:50 PM,7:58,NaN,NaN,Polynice Traveling Turnover (P1.T2),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
35,29600009,37,5,1,1,11:51 PM,7:47,Drexler Bad Pass Turnover (P1.T1),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
36,29600009,38,1,1,1,11:51 PM,7:28,NaN,NaN,Grant 17' Jump Shot (2 PTS) (Williamson 1 AST),...,Kings,SAC,0.0,0,NaN,NaN,NaN,NaN,NaN,0
37,29600009,39,6,1,1,11:51 PM,7:11,NaN,NaN,Grant P.FOUL (P1.T1),...,Kings,SAC,0.0,0,NaN,NaN,NaN,NaN,NaN,0
38,29600009,40,1,1,1,11:52 PM,7:03,Drexler 19' Jump Shot (2 PTS),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
39,29600009,41,2,1,1,11:52 PM,6:47,NaN,NaN,MISS Grant 17' Jump Shot,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
40,29600009,42,4,0,1,11:52 PM,6:46,Olajuwon REBOUND (Off:2 Def:2),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
41,29600009,43,6,2,1,11:52 PM,6:35,NaN,NaN,Grant S.FOUL (P2.T2),...,Kings,SAC,0.0,0,NaN,NaN,NaN,NaN,NaN,0
42,29600009,44,9,1,1,11:52 PM,6:35,ROCKETS Timeout: Regular (Full 1 Short 0),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
43,29600009,45,8,0,1,11:54 PM,6:35,NaN,NaN,SUB: Smith FOR Grant,...,Kings,SAC,0.0,0,NaN,NaN,NaN,NaN,NaN,0
44,29600009,46,3,11,1,11:54 PM,6:35,Willis Free Throw 1 of 2 (1 PTS),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
45,29600009,47,3,12,1,11:55 PM,6:35,Willis Free Throw 2 of 2 (2 PTS),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
46,29600009,48,1,5,1,11:55 PM,6:20,NaN,NaN,Richmond Layup (2 PTS) (Williamson 2 AST),...,Kings,SAC,4.0,0,NaN,1.610613e+09,Houston,Rockets,HOU,0
47,29600009,49,6,2,1,11:55 PM,6:20,Olajuwon S.FOUL (P1.T1),NaN,NaN,...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
48,29600009,50,3,10,1,11:55 PM,6:20,NaN,NaN,Richmond Free Throw 1 of 1 (3 PTS),...,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,0
49,29600009,51,1,1,1,11:56 PM,6:07,Maloney 3PT Jump Shot (5 PTS) (Drexler 3 AST),NaN,NaN,...,Rockets,HOU,0.0,0,NaN,NaN,NaN,NaN,NaN,0